ci:
  autoupdate_commit_msg: "chore: [pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: "monthly"

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-json
    - id: check-yaml
    - id: check-toml
    - id: check-xml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.7.2"
    hooks:
    - id: ruff
      args: ["--fix", "--show-fixes"]
    - id: ruff-format

-   repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"  # replace with latest tag on GitHub
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        files: src
        additional_dependencies: [uhi, numpy]
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the ref you want to point at
    hooks:
    -   id: python-use-type-annotations
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.18  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black
