[tool.poetry]
name = "feynml"
version = "0.0.0"
description = "Feynman diagram markup language"
authors = ["Alexander Puck Neuwirth <alexander@neuwirth-informatik.de>"]
readme = "README.md"
repository = "https://github.com/APN-Pucky/feynml"

[tool.poetry.dependencies]
python = "^3.8"
particle = "*"
xsdata = {version = "*", extras = ["cli","lxml","soap"]}
cssutils = ">=2.10.2"
cssselect = "*"
deprecated = "*"
deprecation = "*"
smpl_io = "^1.1.2"
#smpl_io = {path= "../smpl_io", develop = true}
smpl_doc = "^1.1.3"
#smpl_doc = {path= "../smpl_doc", develop = true}
smpl_util= "^1.0.0"

pyqgraf = {version = ">=0.0.3", optional = true}
#pyqgraf = {path= "../pyqgraf", develop = true }
pyhepmc = {version = "*", optional = true}
pylhe = {version = "*", optional = true}

[tool.poetry.extras]
interfaces = ["pyqgraf", "pyhepmc", "pylhe"]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pyhepmc = "*" # for testing
pylhe = "*" # for testing
pyqgraf = ">=0.0.3" # for testing
pre-commit = ">=2.20,<4.0"
pytest = "*"
pytest-cov =  "*"
pytest-profiling =  "*"
pytest-line-profiler-apn = ">=0.1.3"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
ipython =  "*"
jupyterlab =  "*"
jupyter = "*"
poetry-dynamic-versioning = {extras = ["plugin"], version = ">=0.21.1,<1.3.0"}

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
dirty = true
# modified dunami default pattern without v
pattern = '(?x)(?# ignore whitespace)^((?P<epoch>\d+)!)?(?P<base>\d+(\.\d+)*)(?# v1.2.3 or v1!2000.1.2)([-._]?((?P<stage>[a-zA-Z]+)[-._]?(?P<revision>\d+)?))?(?# b0)(\+(?P<tagged_metadata>.+))?$(?# +linux)'
strict = true
format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}.{{ distance }}{% endif %}"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
addopts = [ "-v", "--cov=feynml", "--cov-config=.coveragerc", "--cov-append", "--cov-report=term", "--cov-report=xml", "--doctest-modules", "--ignore=docs/source/conf.py", "--ignore=debug", "--ignore=debug2" ]
filterwarnings = [
    'error',
    'ignore: pkg_resources is deprecated as an API:DeprecationWarning',
    "ignore: 'cgi' is deprecated and slated for removal in Python 3.13"
]
