name: test

on: 
  push:
    branches:
      - 'master'
    tags-ignore: 
      - '*'

jobs:
    unstable:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-python-latexmk
      steps:
        - uses: APN-Pucky/make-python-action@main
          with:
            test: true
            doc: false
            coveralls: true
            codacy-api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
            test-pypi-token: ${{ secrets.test_pypi_token }}
